version: '3'
services:
  jaya-algo:
    restart: always
    build: ./jaya-algo
    ports:
      - "4008:8000"
    container_name: jaya-algo
  rao-algo:
    restart: always
    build: ./rao-algo
    ports:
      - "4010:8000"
    container_name: rao-algo
  rao2-algo:
    restart: always
    build: ./rao2-algo
    ports:
      - "4012:8000"
    container_name: rao2-algo
  main-container:
    restart: always
    build: ./main-container
    ports:
      - "8000:8000"
    container_name: main-container
