version: '3'
services:
  container-1:
    restart: always
    build: ./django-container-1
    ports:
      - "4000:8000"
  container-2:
    restart: always
    build: ./django-container-2
    ports:
      - "8000:8000"