version: '3'
services:
  insertion-sort:
    restart: always
    build: ./insertion-sort
    ports:
      - "4000:8000"
  quicksort-container:
    restart: always
    build: ./quicksort-container
    ports:
      - "4002:8000"
  
  main-container:
    network_mode: "host"
    restart: always
    build: ./main-container
    ports:
      - "8000:8000"