version: '3'
services:
  insertion-sort:
    restart: always
    build: ./insertion-sort
    ports:
      - "4000:8000"
  quicksort-container:
    restart: always
    build: ./quicksort-container
    ports:
      - "4002:8000"
  bubble-sort:
    restart: always
    build: ./bubble-sort
    ports:
      - "4004:8000"
  selection-sort:
    restart: always
    build: ./selection-sort
    ports:
      - "4006:8000"

  main-container:
    restart: always
    build: ./main-container
    ports:
      - "8000:8000"
